### ISSUE TITLE
gitlab file cleanup

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/solas#37]
There are some things that seem like they could be cleand up in the solas-container and solas-chart gitlab files:

- [x] 1. it would be nice to see [some variables](https://github.com/samsung-cnct/container-kibana/blob/master/.gitlab-ci.yml#L17) 
   ```
   variables:
     quay_org: samsung_cnct
   ```
   more generalized. This way if you want to push to docker hub, you're not setting variables that are named `quay`

- [x] 2. why are some variables lowercase, others capitalized?
   ```
   variables:
     IMAGE_DEVL_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-$CI_JOB_ID
     IMAGE_PROD_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
     registry: quay.io
     image_name: kibana-container
     quay_org: samsung_cnct
     robot_account: kibana_container_rw
     QUAY_PASSWORD: SECRET
   ```

- [x] 3. why have `QUAY_PASSWORD: SECRET` -- if things are going to be a secret in the pipeline, why define this here - its baiting someone to set a password in there and commit it in git.

- [x] 4. why _no_ comments in the build file?  If I'm modifying the buildfile as needed, it would be nice to understand the intent
example - https://git.erie.cluster.cnct.io/venezia/kraken-tools/blob/add_gitlab/.gitlab-ci.yml#L1

- [x] 5. all our variables are defined at the top, but not all are global, should some be moved into the specific stages they are used in?
    - variables that are global in scope for all jobs should be in the variables section
   - variables that are only needed for certain jobs shouldn't be included there
