### ISSUE TITLE
Document common set of labels

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/solas#8]
kraken uses a set of labels which must be recreated for each repo which we add. Either update the documentation to link to a manual process (e.g. https://medium.com/@dtinth/how-to-copy-github-labels-from-one-project-to-another-1857adc73e0f) or automate this in solas.

**Comment by coffeepac** [comment]
@spiffxp I'd like this to be the tracking issue for building a munge-git or similar for CNCT.  Work for you or did you have something stashed elsewhere?

**Comment by spiffxp** [comment]
/assign
I can't guarantee I'll ever get to this in a reasonable timeframe, but I'm going to snag it to keep it on my radar.

The thing we're supposed to be using for kubernetes repos is https://github.com/kubernetes/test-infra/tree/master/label_sync but I'm still not sure what/where the rollout plan for that is.  Presumably if that works happily, we could just schedule the same thing as a CronJob on a cluster of our choice.

**Comment by spiffxp** [comment]
Oh right, /commands don't work here 😅

**Comment by philoserf** [comment]
Terraform can do this now. Worth a look.

https://www.terraform.io/docs/providers/github/r/issue_label.html

**Comment by philoserf** [comment]
So in addition to adding and automating the labels we need to define the canonical set of labels. Has anyone begun that work? Did you assign this to yourself for that purpose @spiffxp ?

**Comment by spiffxp** [comment]
@philoserf if you want it, go for it, like I said, I assigned to keep it on my radar but I'm not anywhere close to having time for this in the "this week" timeframe

**Comment by philoserf** [comment]
An already built solution exists: https://probot.github.io/apps/settings/

The probot is a personal project from inside GitHub that just graduated to the wild. I am dogfooding it on my GitHub account.

The settings bot is exactly what the doctor ordered and fits the solas model.

add a `./github/settings.yml`

```yaml
repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: repo-name

  # A short description of the repository that will show up on GitHub
  description: description of repo

  # A URL with more information about the repository
  homepage: https://example.github.io/

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: true

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: master

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug
    color: CC0000
  - name: feature
    color: 336699
  - name: first-timers-only
    # include the old name to rename and existing label
    oldname: Help Wanted
```

with updated values. This really fits the solas model well for far more than labels.
